version: "3"
services:
  minio:
    image: minio/minio
    restart: unless-stopped
    command: server /data --console-address ":9001"
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      - MINIO_ROOT_USER=admin
      - MINIO_ROOT_PASSWORD=password
  redis:
    image: "redis:latest"
    ports:
      - "6379:6379"
  postgres:
    image: postgres:14.1-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=default_database
    restart: unless-stopped
    ports:
      - "5432:5432"
  worker:
    restart: unless-stopped
    depends_on:
      - postgres
    environment:
      - REDIS_HOST=redis
      - POSTGRES_HOST=postgres
      - AWS_S3_ENDPOINT=http://minio:9000
    build:
      dockerfile: Dockerfile.worker.dev
      context: ./app
  test:
    environment:
      - REDIS_HOST=redis
      - POSTGRES_HOST=postgres
      - AWS_S3_ENDPOINT=http://minio:9000
    depends_on:
      - postgres
    command: sh -c "./wait-for-it/wait-for-it.sh postgres:5432 -- npm run migrate:run ; npm run test:all"
    build:
      dockerfile: Dockerfile.migration.dev
      context: ./app
    volumes:
      - /app/node_modules
      - /app/wait-for-it
      - ./app:/app
